### ISSUE TITLE
service "frappe" is not running in fm.log file

### ISSUE THREAD

**Issue by SujinIn** [rtCamp/Frappe-Manager#143] opened 2024-03-26 18:11 UTC
This issue tracker is only for issues related to Frappe-Manager. Please use https://github.com/rtcamp/frappe-manager/discussions for support questions.

**Describe the bug**
-> I failed create website.

**To Reproduce**
1. Run command '...'
2. See error

Here is error message.
my account name is zfradmin.
And I wrote my typing by Bold.

 
zfradmin@zfrerp:~$ **fm --version**
 0.12.0
zfradmin@zfrerp:~$ **fm create erp --apps erpnext:version-15 --apps hrms:version-15**
✅ fm directory doesn't exists! Created at -> /home/zfradmin/frappe
✅ 🔍 It seems like the first installation. Pulling images... 🖼️
✅ Pulling image ghcr.io/rtcamp/frappe-manager-frappe:v0.12.0 : Done
✅ Pulling image ghcr.io/rtcamp/frappe-manager-nginx:v0.10.0 : Done
✅ Pulling image ghcr.io/rtcamp/frappe-manager-mailhog:v0.8.3 : Done
✅ Pulling image adminer:latest : Done
✅ Pulling image redis:alpine : Done
🚧 Creating services
✅ Pulling services images: Done
✅ Creating services: Done
✅ Creating Compose directories: Done
✅ Starting Docker Containers: Done
⣻ Creating Site
⣟ Creating Site
❌ Failure in generating, supervisor.conf file.The docker command executed was `docker compose -f /home/zfradmin/frappe/sites/erp.localhost/docker-compose.yml exec --user frappe --workdir /workspace/frappe-bench frappe bench setup 
supervisor --skip-redis --skip-supervisord --yes --user frappe`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'service "frappe" is not running'

✅ Rolling back to previous workers configuration.
✅ Workers compose not present. Generating...
✅ Getting Workers info: Done
✅ Starting Workers Containers: Done
❌ There has been some error creating/starting the site.
Please check the logs at /home/zfradmin/frappe/logs/fm.log
🤔 Do you want to remove 'erp.localhost' [yes/no] (no): **yes**
Please select one of the available options
🤔 Do you want to remove 'erp.localhost' [yes/no] (no): **yes**
⚠  Remove DB User: Failed
⚠  Remove DB: Failed
✅ Removing Containers: Done

**Expected behavior**
-> So, I've checked the fm.log file. 

**System information (please complete the following information):**
- [ ] `fm --version` : 0.12.0
- [ ] `lsb_release -a` : No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

- [ ] `docker version` : 25.0.2
- [ ] `docker-compose version` or `docker compose version` : v2.23.3

**Attach log**
Please attach logs from `~/frappe/logs/fm.log` for faster resolution.
[fm.log](https://github.com/rtCamp/Frappe-Manager/files/14762768/fm.log)

**Additional context**

I've instelled from fm v 0.10.0 it worked well. I have some problem from v 0.11.0 version. So I've uninstall frappe-manager and delete the Frappe folder. 
And next install Frappe-manager v 0.12.0 again. but..I have this problem.
Thank you

**Comment by Xieyt** [comment] 2024-03-28 10:05
As I can see in the logs and tried to recreate the issue

This issue arises when a user deletes the fm directory i.e `~/frappe`, and then attempts to use fm, when fm gets invoked it recreated the `~/frappe` directory and also services compose project and with new random secret.

The problem is that when the services got recreated it didn't remove the existing Docker containers and volumes and started the compose project ( old containers got started ).

These containers were initially configured with previous database credentials. However, since these credentials were regenerated upon deletion, they no longer match, leading to authentication failures with the database then the site fails to set up correctly.
Proposed Solution

**Proposed Solution**
To resolve this issue, ensure that docker containers, orphans and volumes are removed when services are recreated.

**Comment by Xieyt** [comment] 2024-03-28 10:12
@SujinIn For now you call follow these steps to fix the issue.
Warning: Since you will be removing `~/frappe` all your data will be deleted.
1. Go to dir `~/frappe/services`, run command `docker compose down -v`.
2. Then delete the dir `~/frappe`.
3. Create site ` fm create erp --apps erpnext:version-15 --apps hrms:version-15`

**Comment by Xieyt** [comment] 2024-03-28 13:35
This is fixed in #147. Will be rolled out in next release.

**Comment by SujinIn** [comment] 2024-03-29 11:56
Ah...So the docker containers are alived.
Thank you very much. Now I can connect to 'erp.localhost' now!!!

**Closed** 2024-03-29 11:56 UTC
Labels: bug
